### ISSUE TITLE
[Issue] panic when running azd up that deploys an api

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1036]
**Output from `azd version`**

```
azd version 0.3.0-beta.5 (commit 38169d7067ac73dc4e214e6913bee5e5359b8b15)
```

**Output from `az version`** 

```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.11",
    "containerapp-compose": "0.2.2"
  }
}
```

**Describe the bug**

When I run azd up on my function app, it provisions everything correctly but fails when it tries to deploy the function.

```

(.venv) pamelafox@Pamelas-MBP-2 deployed-regression-model % azd up                                         

Infrastructure provisioning plan completed successfully
Provisioning Azure resources can take some time.

You can view detailed progress in the Azure Portal:
https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F32ea8a26-5b40-4838-b6cb-be5c89a57c16%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fsalary-model

Created Resource group: salary-model-rg
Created Log Analytics workspace: salary-model-v5dvp62jp2mjg-logworkspace
Created Storage account: salarymodelv5dvp6storage
Created Application Insights: salary-model-v5dvp62jp2mjg-appinsights
Created App Service plan: salary-model-v5dvp62jp2mjg-plan
Created Web App: salary-model-v5dvp62jp2mjg-function-app

Azure resource provisioning completed successfully

Deploying service api...
- Publishing deployment package... /panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4373482]

goroutine 15 [running]:
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.NewResponseError(0x0)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.3/internal/exported/response_error.go:21 +0x42
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.NewResponseError(...)
        /Users/runner/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.3/runtime/errors.go:18
github.com/azure/azure-dev/cli/azd/pkg/azsdk.(*ZipDeployClient).BeginDeploy(0xc0004120c0, {0x47e0798?, 0xc0004126c0?}, {0xc0003ca420?, 0x0?}, {0x47db800?, 0xc00012e060?})
        /Users/runner/work/1/s/cli/azd/pkg/azsdk/zip_deploy_client.go:91 +0x10a
github.com/azure/azure-dev/cli/azd/pkg/azsdk.(*ZipDeployClient).Deploy(0xc00010f8b0?, {0x47e0798, 0xc0004126c0}, {0xc0003ca420?, 0x24?}, {0x47db800?, 0xc00012e060?})
        /Users/runner/work/1/s/cli/azd/pkg/azsdk/zip_deploy_client.go:112 +0x39
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*azCli).DeployFunctionAppUsingZipFile(0x46ec38e?, {0x47e0798, 0xc0004126c0}, {0xc0004b0330?, 0xc00005bd30?}, {0x0?, 0x8?}, {0xc0003ca420, 0xf}, {0x47db800, ...})
        /Users/runner/work/1/s/cli/azd/pkg/tools/azcli/function_app.go:48 +0x6e
github.com/azure/azure-dev/cli/azd/pkg/project.(*functionAppTarget).Deploy(0xc000412660, {0x47e0798, 0xc0004126c0}, 0x0?, {0xc0005be300, 0x3e}, 0x4103025?)
        /Users/runner/work/1/s/cli/azd/pkg/project/service_target_functionapp.go:54 +0x30b
github.com/azure/azure-dev/cli/azd/pkg/project.(*Service).Deploy.func1()
        /Users/runner/work/1/s/cli/azd/pkg/project/service.go:71 +0x3c2
created by github.com/azure/azure-dev/cli/azd/pkg/project.(*Service).Deploy
        /Users/runner/work/1/s/cli/azd/pkg/project/service.go:52 +0x10c
```

**To Reproduce**

1. git clone https://github.com/pamelafox/regression-model-azure-demo (at commit 991ab24fc575dfcd0015fcd49a0bc0d7447b553e)
3. Run azd up 

**Environment**

Information on your environment: 

I have replicated both in VS Code and in the terminal (not inside a venv or devcontainer). I'm on an M1 Mac, running Ventura OS version.

VS Code
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z (2 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Additional context**

If I separately run azd provision, it succeeds, but azd deploy still fails (which makes sense since the problem is at the deployment stage).

**Comment by pamelafox** [comment]
Hm, it looks like https://github.com/Azure/azure-dev/pull/1008/files may have fixed this, but I thought the latest version (beta.5) had that fix. I might be misreading the git tags. I'll try to get the azd version from that PR.

**Comment by pamelafox** [comment]
Update: I grabbed the azd from that PR and I no longer get a nil pointer, I get an actual error. I'll close this.

**Comment by vhvb1989** [comment]
> Hm, it looks like https://github.com/Azure/azure-dev/pull/1008/files may have fixed this, but I thought the latest version (beta.5) had that fix. I might be misreading the git tags. I'll try to get the azd version from that PR.

version beta.5 was a hotfix for beta.3.   It is basically beta.3 + hotfix for non-string output parameters.

beta.4 was deprecated as it contains other issues on top of beta.3.

The beta.6 should be released soon to be on top of latest main branch
