### ISSUE TITLE
Java app service fails to load

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1214]
After: https://github.com/Azure/azure-dev/pull/1122

test templates pipeline started to fail for java: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2017249&view=logs&j=44dd46f8-84ab-573d-dca7-b546157951bd&t=ec40f08b-0364-50b1-fec5-83e3f289707c

It looks like the api server is unable to start.

currently investigating...

**Comment by vhvb1989** [comment]
I was able to launch and run the `api` and `web` apps locally.
It is the `deploy` operation the one which might be not working, as the `api` on Azure doesn't work

**Comment by weikanglim** [comment]
Seeing the following exception in application logs:
```
2022-11-29T17:26:02.568075655Z Exception in thread "main" java.lang.reflect.InvocationTargetException
2022-11-29T17:26:02.568946711Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-29T17:26:02.575477337Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-11-29T17:26:02.575783257Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-29T17:26:02.576055175Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-11-29T17:26:02.576075376Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2022-11-29T17:26:02.576522205Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
2022-11-29T17:26:02.577258253Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2022-11-29T17:26:02.577284255Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2022-11-29T17:26:02.577289755Z Caused by: io.opentelemetry.contrib.attach.RuntimeAttachException: A problem has occurred during the runtime attachment of the Java agent.
2022-11-29T17:26:02.579177378Z 	at io.opentelemetry.contrib.attach.CoreRuntimeAttach.handleByteBuddyException(CoreRuntimeAttach.java:98)
2022-11-29T17:26:02.579195579Z 	at io.opentelemetry.contrib.attach.CoreRuntimeAttach.attachJavaagentToCurrentJVM(CoreRuntimeAttach.java:47)
2022-11-29T17:26:02.585260375Z 	at com.microsoft.applicationinsights.attach.ApplicationInsights.attach(ApplicationInsights.java:69)
2022-11-29T17:26:02.585502790Z 	at com.microsoft.azure.simpletodo.SimpleTodoApplication.main(SimpleTodoApplication.java:12)
2022-11-29T17:26:02.585516191Z 	... 8 more
2022-11-29T17:26:02.585787909Z Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
2022-11-29T17:26:02.586034725Z 	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:700)
2022-11-29T17:26:02.588668597Z 	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:631)
2022-11-29T17:26:02.588687598Z 	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:298)
2022-11-29T17:26:02.588693198Z 	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:263)
2022-11-29T17:26:02.588697598Z 	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:245)
2022-11-29T17:26:02.588701799Z 	at io.opentelemetry.contrib.attach.CoreRuntimeAttach.attachJavaagentToCurrentJVM(CoreRuntimeAttach.java:45)
```
