### ISSUE TITLE
azd pipeline config throws "panic: runtime error: index out of range [1] with length 1"

### ISSUE THREAD

**Issue by EverybodyKurts** [Azure/azure-dev#1945]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```bash
% azd version
azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)
```

**Describe the bug**

Running the `azd pipeline config` command results in a runtime error exception:

```bash
% azd pipeline config                

Configure your azd pipeline

You need an Azure DevOps Personal Access Token (PAT). Please create a PAT by following the instructions here https://aka.ms/azure-dev/azdo-pat
(skip this prompt by setting the PAT to env var: AZURE_DEVOPS_EXT_PAT)
? Personal Access Token (PAT): skip

  (✓) Done: Checking current directory for Git repository
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/commands/pipeline.(*AzdoScmProvider).gitRepoDetails(0xc000557700, {0x100bb1190, 0xc00053d6e0}, {0xc000044200, 0x35})
        /Users/runner/work/1/s/cli/azd/pkg/commands/pipeline/azdo_provider.go:480 +0xb85
github.com/azure/azure-dev/cli/azd/pkg/commands/pipeline.(*PipelineManager).ensureRemote(0xc00037a840, {0x100bb1190, 0xc00053d6e0}, {0xc000044044?, 0x2d?}, {0x100a62e26?, 0xc000468800?})
        /Users/runner/work/1/s/cli/azd/pkg/commands/pipeline/pipeline_manager.go:146 +0xd1
github.com/azure/azure-dev/cli/azd/pkg/commands/pipeline.(*PipelineManager).getGitRepoDetails(0xc00037a840, {0x100bb1190, 0xc00053d6e0})
        /Users/runner/work/1/s/cli/azd/pkg/commands/pipeline/pipeline_manager.go:171 +0x1c5
github.com/azure/azure-dev/cli/azd/pkg/commands/pipeline.(*PipelineManager).Configure(0xc00037a840, {0x100bb1190, 0xc00053d6e0})
        /Users/runner/work/1/s/cli/azd/pkg/commands/pipeline/pipeline_manager.go:306 +0x25b
github.com/azure/azure-dev/cli/azd/cmd.(*pipelineConfigAction).Run(0xc000546300, {0x100bb1190, 0xc00053d6e0})
        /Users/runner/work/1/s/cli/azd/cmd/pipeline.go:164 +0x22c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x100bb1190?, 0xc00053d6e0?})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:127 +0x23e
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0xc0001b4048, {0x100bb1190, 0xc00053c720}, 0xc0000d4040)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/telemetry.go:60 +0x645
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x100bb1190, 0xc00053c720})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x1f2
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*DebugMiddleware).Run(0xc00052e030, {0x100bb1190, 0xc00053c720}, 0xc0000d4040)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/debug.go:48 +0x2b0
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x100bb1190, 0xc00053c720})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x1f2
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction(0xc0004ba990, {0x100bb1190, 0xc00053c720}, 0x100872460?, {0x100ba7d40?, 0xc000546300})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:131 +0x23d
github.com/azure/azure-dev/cli/azd/cmd.(*CobraBuilder).configureActionResolver.func1(0xc0004adb80, {0x101159930?, 0x0, 0x0})
        /Users/runner/work/1/s/cli/azd/cmd/cobra_builder.go:134 +0x49b
github.com/spf13/cobra.(*Command).execute(0xc0004adb80, {0x101159930, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000484a00)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(0xc0001c0000?, {0x100bb1120?, 0xc0001a8000?})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895 +0x4a
main.main()
        /Users/runner/work/1/s/cli/azd/main.go:57 +0x159
```

**To Reproduce**

Below is my `azure.yaml` file:

```yaml
name: myapp
services:
  webApp:
    project: ./webapp
    # sveltekit packages static apps in "build/static"
    dist: build/static
    language: ts
    host: staticwebapp
    hooks:
      predeploy:
        shell: sh
        run: vite build
pipeline:
  provider: azdo
```

Let me know if I need to include any additional information.

**Expected behavior**

Either a successful pipeline configuration or a more descriptive error message.

**Comment by vhvb1989** [comment]
This issue occurs when cloning the repository from Azure DevOps using `ssh`.
If you run `git remote -v`, you would see a remote set for the local repository, and azd is trying to use that remote to set the pipeline.

You can fix this by running `git remote remove origin` to disconnect the repo from the remote repository (using ssh).  Then run `azd pipeline config` and now azd will ask you if you want to pick an existing repo from Azure DevOps or create a new one. 
Azd will use the PAT (and not ssh).

I don't think azd will be supporting `ssh` for Azure DevOps, but I will improve the error message here instead of the current panic
