### ISSUE TITLE
[Issue] The azd feature doesn't work for some dev containers

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2547]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

Whatever version is used by the azd feature.

**Describe the bug**

We are trying to add the azd feature to our repo, but we get a bug upon building.

Here's a snippet from the logs:

```
[2023-07-17T17:22:12.587Z]  => ERROR [internal] load metadata for docker.io/library/dev_container_fe  2.3s
 => CANCELED [internal] load metadata for docker.io/library/python:3.11    2.3s
 => [auth] library/python:pull token for registry-1.docker.io              0.0s
 => [auth] library/dev_container_feature_content_temp:pull token for regi  0.0s
------
 > [internal] load metadata for docker.io/library/dev_container_feature_content_temp:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
[2023-07-17T17:22:12.605Z] Stop (2925 ms): Run: docker-compose --project-name azure-django-postgres-aca-fork -f /Users/pamelafox/azure-django-postgres-aca-fork/docker-compose.yml -f /Users/pamelafox/azure-django-postgres-aca-fork/.devcontainer/docker-compose_dev.yml -f /Users/pamelafox/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1689614529680.yml build
[2023-07-17T17:22:12.605Z] Error: Command failed: docker-compose --project-name azure-django-postgres-aca-fork -f /Users/pamelafox/azure-django-postgres-aca-fork/docker-compose.yml -f /Users/pamelafox/azure-django-postgres-aca-fork/.devcontainer/docker-compose_dev.yml -f /Users/pamelafox/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1689614529680.yml build
[2023-07-17T17:22:12.606Z]     at fC (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:1995:412)
[2023-07-17T17:22:12.606Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-07-17T17:22:12.606Z]     at async qte (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:1995:2381)
[2023-07-17T17:22:12.606Z]     at async Ute (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:1977:3170)
[2023-07-17T17:22:12.606Z]     at async hre (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:2047:3833)
[2023-07-17T17:22:12.606Z]     at async Zf (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:2047:4775)
[2023-07-17T17:22:12.606Z]     at async Bne (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:2179:12193)
[2023-07-17T17:22:12.606Z]     at async Rne (/Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js:2179:11934)
[2023-07-17T17:22:12.612Z] Stop (9785 ms): Run: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/pamelafox/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-7cfebeec-52da-40ef-b12c-9e02da1584741689614521551 --workspace-folder /Users/pamelafox/azure-django-postgres-aca-fork --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/pamelafox/azure-django-postgres-aca-fork --id-label devcontainer.config_file=/Users/pamelafox/azure-django-postgres-aca-fork/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/pamelafox/azure-django-postgres-aca-fork/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-07-17T17:22:12.612Z] Exit code 1
[2023-07-17T17:22:12.616Z] Command failed: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/pamelafox/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.301.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/pamelafox/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-7cfebeec-52da-40ef-b12c-9e02da1584741689614521551 --workspace-folder /Users/pamelafox/azure-django-postgres-aca-fork --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/pamelafox/azure-django-postgres-aca-fork --id-label devcontainer.config_file=/Users/pamelafox/azure-django-postgres-aca-fork/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/pamelafox/azure-django-postgres-aca-fork/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-07-17T17:22:12.616Z] Exit code 1
```

**To Reproduce**

Git checkout this branch:

https://github.com/Azure-Samples/azure-django-postgres-aca/compare/main...pamelafox:azure-django-postgres-aca-fork:add-azd-feat?expand=1

Try to open in a dev container in VS Code on Mac M1.

**Environment**

Information on your environment:

Version: 1.80.0-insider (Universal)
Commit: 39efe30bfc8e196f5be2119479092bd9eb83e174
Date: 2023-06-30T14:34:06.522Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Docker version:
"You're currently on version 4.17.0 (99724). The latest version is 4.20.1 (110738)."

**Comment by pamelafox** [comment]
cc @kjaymiller

**Comment by ellismg** [comment]
Just to confirm something I think you mentioned internally, @pamelafox, you've only ever seen this when using docker-compose, right?  When using just a single container for the devcontainer which doesn't involve compose things work as expected?

**Comment by pamelafox** [comment]
Yes, and actually, even my simpler docker-compose ones are working fine with the new feature, like https://github.com/pamelafox/django-quiz-app
This one is more complex as it references multiple docker-compose files that are merged together. Not sure if thats the issue or if there's another aspect of the devcontainer.json that's throwing it off.

**Comment by rajeshkamal5050** [comment]
@hemarina can you investigate on this?

**Comment by weikanglim** [comment]
@pamelafox Does it work if we remove this [line](https://github.com/pamelafox/azure-django-postgres-aca-fork/blob/add-azd-feat/docker-compose.yml#L21) in docker-compose.yml, to run the local application in arm64 mode? I tested this change with @hemarina today, and it seems to work on my M1 laptop. I think this is what I'd do for software I write as well. The app will still be deployed to ACA cross-compiled for `amd64`, but locally it runs with `arm64`.

What we suspect was happening is that the multiple layers of docker build wasn't working well when the base image was using `arm64`, but one of the compose images was using `amd64`.

**Comment by pamelafox** [comment]
Ah, that was it! Sorry I missed that line, that makes sense.
