### ISSUE TITLE
[pipeline config] seg fault when trying to create service principal

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2973]
Looks like a missing error check

error:
```
vivazqu@dev-box-vivazqu:~/workspace/build/pp$ azd pipeline config --principal-name foooooo

Configure your GitHub pipeline

  (✓) Done: Checking current directory for Git repository
  |=====  | Creating service principal foooooopanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x556ddeee9803]

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/pipeline.(*PipelineManager).Configure(0xc0001ea7e0, {0x556ddf83bd08, 0xc00032c8d0})
        /mnt/vss/_work/1/s/cli/azd/pkg/pipeline/pipeline_manager.go:246 +0xa63
github.com/azure/azure-dev/cli/azd/cmd.(*pipelineConfigAction).Run(0xc00010ea00, {0x556ddf83bd08, 0xc00032c8d0})
        /mnt/vss/_work/1/s/cli/azd/cmd/pipeline.go:174 +0x27e
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x556ddf83bd08?, 0xc00032c8d0?})
        /mnt/vss/_work/1/s/cli/azd/cmd/middleware/middleware.go:127 +0x2e8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0xc000111d30, {0x556ddf83bd08, 0xc0004ef980}, 0xc0005aeb80)
        /mnt/vss/_work/1/s/cli/azd/cmd/middleware/telemetry.go:85 +0x8b8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x556ddf83bd08, 0xc0004ef980})
        /mnt/vss/_work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x2a2
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*ExperimentationMiddleware).Run(0x556ddf0c0f0f?, {0x556ddf83bd08, 0xc0004ef980}, 0xc0005aeb80)
        /mnt/vss/_work/1/s/cli/azd/cmd/middleware/experimentation.go:64 +0x4d6
```

![image](https://github.com/Azure/azure-dev/assets/24213737/512c2af2-f574-406e-a141-28cc1931e04b)

err is not check for non-nil before trying to use the sp

**Comment by vhvb1989** [comment]
After checking the error:

![image](https://github.com/Azure/azure-dev/assets/24213737/25707ee0-84ea-4934-a1e6-94b9cfc9d601)
