### ISSUE TITLE
Racy access to map in developer_client.go

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3003]
Saw this failure in a CI run:

```
2023-11-17T22:12:51.4073100Z === FAIL: cli/azd/pkg/devcenter Test_TemplateSource_ListTemplates/Fail (unknown)
2023-11-17T22:12:51.4073916Z fatal error: concurrent map read and map write
2023-11-17T22:12:51.4074298Z 
2023-11-17T22:12:51.4074969Z goroutine 102 [running]:
2023-11-17T22:12:51.4076123Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).devCenterList(0xc000565f80, {0xb2a720, 0xe27dc0})
2023-11-17T22:12:51.4077284Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:184 +0x7e
2023-11-17T22:12:51.4078639Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).host(0x688db8?, {0xb2a720?, 0xe27dc0?}, 0xc000068aa0)
2023-11-17T22:12:51.4079793Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:215 +0x2f
2023-11-17T22:12:51.4081218Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EntityListRequestBuilder[...]).createRequest(0x22, {0xb2a720?, 0xe27dc0}, {0xa78bab, 0x3}, {0xc000324ae0, 0x28})
2023-11-17T22:12:51.4082579Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/entity_list_request_builder.go:44 +0x6b
2023-11-17T22:12:51.4083907Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EnvironmentDefinitionListRequestBuilder).Get(0xc000494d50, {0xb2a720, 0xe27dc0})
2023-11-17T22:12:51.4085211Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/environment_definition_request_builders.go:41 +0x129
2023-11-17T22:12:51.4086902Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func3(0xdc9820)
2023-11-17T22:12:51.4088246Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:85 +0x3fe
2023-11-17T22:12:51.4089399Z created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 100
2023-11-17T22:12:51.4090474Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:73 +0x233
2023-11-17T22:12:51.4090943Z 
2023-11-17T22:12:51.4091511Z goroutine 1 [chan receive]:
2023-11-17T22:12:51.4092193Z testing.(*T).Run(0xc00033e340, {0xa8bb89?, 0x67390d?}, 0xabc000)
2023-11-17T22:12:51.4093064Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1649 +0x3c8
2023-11-17T22:12:51.4093830Z testing.runTests.func1(0xdd2420?)
2023-11-17T22:12:51.4094591Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:2054 +0x3e
2023-11-17T22:12:51.4095473Z testing.tRunner(0xc00033e340, 0xc0002dfc38)
2023-11-17T22:12:51.4096263Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1595 +0xff
2023-11-17T22:12:51.4097233Z testing.runTests(0xc00037c460?, {0xdcb2c0, 0x14, 0x14}, {0xe28fa0?, 0xc0002dfcf8?, 0xdd1920?})
2023-11-17T22:12:51.4098212Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:2052 +0x445
2023-11-17T22:12:51.4098972Z testing.(*M).Run(0xc00037c460)
2023-11-17T22:12:51.4099717Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1925 +0x636
2023-11-17T22:12:51.4100476Z main.main()
2023-11-17T22:12:51.4100999Z 	_testmain.go:119 +0x1bf
2023-11-17T22:12:51.4101313Z 
2023-11-17T22:12:51.4101886Z goroutine 91 [chan receive]:
2023-11-17T22:12:51.4102572Z testing.(*T).Run(0xc00049c340, {0xa78e74?, 0x45266786e0c?}, 0xabc2f0)
2023-11-17T22:12:51.4103455Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1649 +0x3c8
2023-11-17T22:12:51.4104568Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.Test_TemplateSource_ListTemplates(0xc0004bf380?)
2023-11-17T22:12:51.4105619Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source_test.go:143 +0xa5
2023-11-17T22:12:51.4106417Z testing.tRunner(0xc00049c340, 0xabc000)
2023-11-17T22:12:51.4107193Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1595 +0xff
2023-11-17T22:12:51.4107986Z created by testing.(*T).Run in goroutine 1
2023-11-17T22:12:51.4109567Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1648 +0x3ad
2023-11-17T22:12:51.4110226Z 
2023-11-17T22:12:51.4110813Z goroutine 100 [semacquire]:
2023-11-17T22:12:51.4111402Z sync.runtime_Semacquire(0xc000352680?)
2023-11-17T22:12:51.4113006Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/runtime/sema.go:62 +0x25
2023-11-17T22:12:51.4114121Z sync.(*WaitGroup).Wait(0xc000483ea0?)
2023-11-17T22:12:51.4115285Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/sync/waitgroup.go:116 +0x48
2023-11-17T22:12:51.4116552Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates(0xc00041f830, {0xb2a720?, 0xe27dc0})
2023-11-17T22:12:51.4117687Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:183 +0x527
2023-11-17T22:12:51.4118787Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.Test_TemplateSource_ListTemplates.func5(0x0?)
2023-11-17T22:12:51.4120003Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source_test.go:150 +0x9f
2023-11-17T22:12:51.4120797Z testing.tRunner(0xc00049d380, 0xabc2f0)
2023-11-17T22:12:51.4121675Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1595 +0xff
2023-11-17T22:12:51.4122372Z created by testing.(*T).Run in goroutine 91
2023-11-17T22:12:51.4123530Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/testing/testing.go:1648 +0x3ad
2023-11-17T22:12:51.4124071Z 
2023-11-17T22:12:51.4124438Z goroutine 107 [chan receive]:
2023-11-17T22:12:51.4125182Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func6()
2023-11-17T22:12:51.4126002Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:177 +0x7f
2023-11-17T22:12:51.4126956Z created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 100
2023-11-17T22:12:51.4127850Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:174 +0x513
2023-11-17T22:12:51.4128832Z 
2023-11-17T22:12:51.4129200Z goroutine 106 [chan receive]:
2023-11-17T22:12:51.4129933Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func5()
2023-11-17T22:12:51.4130750Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:163 +0x8c
2023-11-17T22:12:51.4131685Z created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 100
2023-11-17T22:12:51.4132568Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:160 +0x49f
2023-11-17T22:12:51.4132988Z 
2023-11-17T22:12:51.4133324Z goroutine 105 [semacquire]:
2023-11-17T22:12:51.4133743Z sync.runtime_Semacquire(0x74c1e0?)
2023-11-17T22:12:51.4134308Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/runtime/sema.go:62 +0x25
2023-11-17T22:12:51.4134890Z sync.(*WaitGroup).Wait(0xc0004d7fd0?)
2023-11-17T22:12:51.4135511Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/sync/waitgroup.go:116 +0x48
2023-11-17T22:12:51.4136393Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func4()
2023-11-17T22:12:51.4137201Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:149 +0x33
2023-11-17T22:12:51.4138145Z created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 100
2023-11-17T22:12:51.4139027Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:148 +0x3d9
2023-11-17T22:12:51.4139483Z 
2023-11-17T22:12:51.4139824Z goroutine 101 [runnable]:
2023-11-17T22:12:51.4140378Z fmt.(*pp).doPrintf(0xc0000ae000, {0xa8d9b5, 0x23}, {0xc00018d0e0?, 0x1, 0x1})
2023-11-17T22:12:51.4141104Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/fmt/print.go:1021 +0x11bf
2023-11-17T22:12:51.4141753Z fmt.Sprintf({0xa8d9b5, 0x23}, {0xc00018d0e0, 0x1, 0x1})
2023-11-17T22:12:51.4142379Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/fmt/print.go:239 +0x53
2023-11-17T22:12:51.4143367Z github.com/azure/azure-dev/cli/azd/test/mocks/mockdevcentersdk.MockListEnvironmentDefinitions.func1(0xc000151700)
2023-11-17T22:12:51.4144316Z 	D:/a/_work/1/s/cli/azd/test/mocks/mockdevcentersdk/mocks.go:263 +0x7c
2023-11-17T22:12:51.4145274Z github.com/azure/azure-dev/cli/azd/test/mocks/mockhttp.(*MockHttpClient).Do(0xc0000fe378, 0xc000151700)
2023-11-17T22:12:51.4146174Z 	D:/a/_work/1/s/cli/azd/test/mocks/mockhttp/mock_http_client.go:33 +0x62
2023-11-17T22:12:51.4147276Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.transportPolicy.Do({{0x2b7e3a85418?, 0xc0000fe378?}}, 0xc0003eab01?)
2023-11-17T22:12:51.4148721Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/pipeline.go:50 +0x34
2023-11-17T22:12:51.4149864Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028af00)
2023-11-17T22:12:51.4151010Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4152101Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.bodyDownloadPolicy(0xc00028af00)
2023-11-17T22:12:51.4153297Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_body_download.go:20 +0x1c
2023-11-17T22:12:51.4154496Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.PolicyFunc.Do(0x687250?, 0xc00018d308?)
2023-11-17T22:12:51.4155674Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:181 +0x19
2023-11-17T22:12:51.4156803Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028aec0)
2023-11-17T22:12:51.4157942Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4159012Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.httpHeaderPolicy(0xc00028aec0)
2023-11-17T22:12:51.4160116Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_http_header.go:31 +0xbd
2023-11-17T22:12:51.4161289Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.PolicyFunc.Do(0x67390d?, 0x6557e54a?)
2023-11-17T22:12:51.4162470Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:181 +0x19
2023-11-17T22:12:51.4163603Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ae80)
2023-11-17T22:12:51.4164728Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4165890Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*logPolicy).Do(0xc0000fe3d8, 0xc00028ae80)
2023-11-17T22:12:51.4167024Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_logging.go:122 +0x3ad
2023-11-17T22:12:51.4168144Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ae40)
2023-11-17T22:12:51.4169270Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4170441Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*BearerTokenPolicy).Do(0xc000429740, 0xc00028ae40)
2023-11-17T22:12:51.4171639Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_bearer_token.go:85 +0x11c
2023-11-17T22:12:51.4172759Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ae00)
2023-11-17T22:12:51.4173894Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4175000Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*retryPolicy).Do(0x0?, 0xc00028ae00)
2023-11-17T22:12:51.4176142Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_retry.go:128 +0x5b3
2023-11-17T22:12:51.4177247Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028adc0)
2023-11-17T22:12:51.4178371Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4179508Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*apiVersionPolicy).Do(0x40?, 0xc00028adc0)
2023-11-17T22:12:51.4180371Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/api_version_policy.go:37 +0xe5
2023-11-17T22:12:51.4181274Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ad80)
2023-11-17T22:12:51.4182491Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4183563Z github.com/azure/azure-dev/cli/azd/pkg/azsdk.(*noOptPolicy).Do(0x0?, 0xc00018d9c0?)
2023-11-17T22:12:51.4184337Z 	D:/a/_work/1/s/cli/azd/pkg/azsdk/correlation_policy.go:22 +0x16
2023-11-17T22:12:51.4185205Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ad40)
2023-11-17T22:12:51.4186405Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4187538Z github.com/azure/azure-dev/cli/azd/pkg/azsdk.(*userAgentPolicy).Do(0xc000351dc0, 0xc00028ad40)
2023-11-17T22:12:51.4188345Z 	D:/a/_work/1/s/cli/azd/pkg/azsdk/user_agent_policy.go:35 +0x1e5
2023-11-17T22:12:51.4189208Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ad00)
2023-11-17T22:12:51.4190336Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4191564Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.telemetryPolicy.Do({{0xc000458150?, 0xa3bc80?}}, 0xc00028ad00)
2023-11-17T22:12:51.4192778Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_telemetry.go:66 +0x1b4
2023-11-17T22:12:51.4193894Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028acc0)
2023-11-17T22:12:51.4195023Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4196116Z github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.includeResponsePolicy(0xc00028acc0)
2023-11-17T22:12:51.4197262Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/runtime/policy_include_response.go:19 +0x1c
2023-11-17T22:12:51.4198388Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.PolicyFunc.Do(0x0?, 0x0?)
2023-11-17T22:12:51.4199506Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:181 +0x19
2023-11-17T22:12:51.4200621Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00028ac80)
2023-11-17T22:12:51.4201744Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/request.go:84 +0xf0
2023-11-17T22:12:51.4203020Z github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.Pipeline.Do({{0xc000588780?, 0x22?, 0xb2a720?}}, 0xc00028ac80)
2023-11-17T22:12:51.4204306Z 	C:/Users/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.6.0/internal/exported/pipeline.go:96 +0x185
2023-11-17T22:12:51.4205630Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EnvironmentDefinitionListRequestBuilder).Get(0xc00041a450, {0xb2a720, 0xe27dc0})
2023-11-17T22:12:51.4206772Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/environment_definition_request_builders.go:46 +0x199
2023-11-17T22:12:51.4207797Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func3(0xdc97c0)
2023-11-17T22:12:51.4208634Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:85 +0x3fe
2023-11-17T22:12:51.4209575Z created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 100
2023-11-17T22:12:51.4210447Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:73 +0x233
2023-11-17T22:12:51.4210859Z 
2023-11-17T22:12:51.4211196Z goroutine 103 [runnable]:
2023-11-17T22:12:51.4211674Z sync.runtime_SemacquireMutex(0xc000191860?, 0xcf?, 0x10?)
2023-11-17T22:12:51.4212320Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/runtime/sema.go:77 +0x25
2023-11-17T22:12:51.4212899Z sync.(*Mutex).lockSlow(0xc000565fc0)
2023-11-17T22:12:51.4213466Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/sync/mutex.go:171 +0x15d
2023-11-17T22:12:51.4214106Z sync.(*Mutex).Lock(...)
2023-11-17T22:12:51.4214593Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/sync/mutex.go:90
2023-11-17T22:12:51.4215132Z sync.(*RWMutex).Lock(0xc000188168?)
2023-11-17T22:12:51.4215695Z 	C:/hostedtoolcache/windows/go/1.21.0/x64/src/sync/rwmutex.go:147 +0x31
2023-11-17T22:12:51.4216706Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).projectList(0xc000565f80, {0xb2a720, 0xe27dc0})
2023-11-17T22:12:51.4217655Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:136 +0xaad
2023-11-17T22:12:51.4218760Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).devCenterList(0xc000565f80, {0xb2a720, 0xe27dc0})
2023-11-17T22:12:51.4219716Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:190 +0xff
2023-11-17T22:12:51.4220752Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).host(0x688db8?, {0xb2a720?, 0xe27dc0?}, 0xc000068910)
2023-11-17T22:12:51.4221713Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:215 +0x2f
2023-11-17T22:12:51.4222934Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EntityListRequestBuilder[...]).createRequest(0x22, {0xb2a720?, 0xe27dc0}, {0xa78bab, 0x3}, {0xc000324a20, 0x28})
2023-11-17T22:12:51.4224098Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/entity_list_request_builder.go:44 +0x6b
2023-11-17T22:12:51.4225243Z github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EnvironmentDefinitionListRequestBuilder).Get(0xc0004947b0, {0xb2a720, 0xe27dc0})
2023-11-17T22:12:51.4226363Z 	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/environment_definition_request_builders.go:41 +0x129
2023-11-17T22:12:51.4227393Z github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func3(0xdc9880)
2023-11-17T22:12:51.4228221Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:85 +0x3fe
2023-11-17T22:12:51.4229159Z created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 100
2023-11-17T22:12:51.4230034Z 	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:73 +0x233
2023-11-17T22:12:51.4230447Z 
```

In `developer_client.go` we do have a mutex that we use to control access the the `cache` local variable - but it looks like we only ever grab the mutex when we are writing to the map.  We need all concurrent access guarded so reads and writes can't interleave as they do today.

**Comment by weikanglim** [comment]
Fixed with #3437
