### ISSUE TITLE
Packaging error: The "fileName" or "name" properties of emitted chunks and assets must be strings that are neither absolute nor relative paths

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#3006]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
This just started with version 1.5.0, which I installed this morning.

**I always use folders on C:/ that are junctions/links to folders on another drive.**
In this case I have C:/Temp linked to D:/Temp.

From C:/Temp, when I run `azd init --template azure-search-openai-demo`, followed by `azd up` I get this error (note the file path below is d:/Temp"

``` 
  | ======| Packaging service backendvite v4.4.11 building for production...
✓ 2754 modules transformed.
  |====   | Packaging service backend[vite:build-html] The "fileName" or "name" properties of emitted chunks and assets must be strings that are neither absolute nor relative paths, received "d:/Temp/deleteme/app/frontend/index.html".
✓ built in 10.64s
error during build:
RollupError: The "fileName" or "name" properties of emitted chunks and assets must be strings that are neither absolute nor relative paths, received "d:/Temp/deleteme/app/frontend/index.html".
    at error (file:///d:/Temp/deleteme/app/frontend/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at FileEmitter.emitFile (file:///d:/Temp/deleteme/app/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25039:24)
    at Object.generateBundle (file:///d:/Temp/deleteme/app/frontend/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:37924:22)
    at async Bundle.generate (file:///d:/Temp/deleteme/app/frontend/node_modules/rollup/dist/es/shared/node-entry.js:17930:9)
    at async file:///d:/Temp/deleteme/app/frontend/node_modules/rollup/dist/es/shared/node-entry.js:26785:27
    at async catchUnfinishedHookActions (file:///d:/Temp/deleteme/app/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async build (file:///d:/Temp/deleteme/app/frontend/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:48074:22)
    at async CAC.<anonymous> (file:///d:/Temp/deleteme/app/frontend/node_modules/vite/dist/node/cli.js:842:9)
  (x) Failed: Packaging service backend

ERROR: failed packaging service 'backend': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '1', Path: 'C:\Users\charris\AppData\Local\Temp\azd-prepackage-3002631476.ps1'. : exit code: 1
```

**To Reproduce**
1. On Windows, create a folder called `d:\temp`
2. Open a command prompt (not PowerShell) as Admin and run `mklink c:\temp d:\temp`
3. From `c:\temp` run `azd init -t azure-search-openai-demo`
4. Run `azd up`

**Expected behavior**
`azd up` runs successfully with no errors.

**Environment**
Information on your environment:
    * Windows 11

**Additional context**
**I always use folders on C:/ that are junctions/links to folders on another drive.**
The recent update doesn't like the junction anymore.

**Comment by rajeshkamal5050** [comment]
This issue has been open for over 2 years without substantive activity — no comments, no linked PRs, and no description updates.

To keep our backlog healthy and actionable, we're closing it as not planned.

If this is still relevant, please comment and we'll reopen it. Thank you!

/cc @kristenwomack

**Comment by rajeshkamal5050** [comment]
This issue has been open for over 2 years without substantive activity — no comments, no linked PRs, and no description updates.

To keep our backlog healthy and actionable, we're closing it as not planned.

If this is still relevant, please comment and we'll reopen it. Thank you!

/cc @kristenwomack
