### ISSUE TITLE
[Issue] azd init crashes for .NET Aspire app when including custom container

### ISSUE THREAD

**Issue by akade** [Azure/azure-dev#3016]
**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
When running `azd init` for a .NET Apsire project that includes a custom container in a .NET Aspire Project, the cli crashes with the following output:

```
Initializing an app to run on Azure (azd init)

? How do you want to initialize your app? Use code in the current directory

  (✓) Done: Scanning app code in current directory

Detected services:

  .NET (Aspire)
  Detected in: C:\Source\SolutionFolder\Project.AppHost\Project.AppHost.csproj

azd will generate the files necessary to host your app on Azure using Azure Container Apps.

? Select an option Confirm and continue initializing my app
By default, a service can only be reached from inside the Azure Container Apps environment it is running in. Selecting a service here will also allow it to be reached from the Internet.
? Select which services to expose to the Internet project-server
? Enter a new environment name: [? for help] projectname

? Enter a new environment name: projectname

Generating files to run your app on Azure:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa64ee1]

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).Compile(0xc0005aac10)
        github.com/azure/azure-dev/cli/azd/pkg/apphost/generate.go:409 +0x121
github.com/azure/azure-dev/cli/azd/pkg/apphost.GenerateProjectArtifacts({0xec95e0?, 0xc0005abfc8?}, {0xc0006997a0?, 0x4d?}, {0xc0006997b9, 0x16}, 0xc00063daa8?, {0xc0005543c0?, 0x0?})
        github.com/azure/azure-dev/cli/azd/pkg/apphost/generate.go:131 +0x596
github.com/azure/azure-dev/cli/azd/internal/repository.(*Initializer).InitFromApp(0xc000048d80, {0x1251ec0, 0xc0000bc330}, 0xc00017a530, 0xc0005acd00)
        github.com/azure/azure-dev/cli/azd/internal/repository/app_init.go:167 +0x1157
github.com/azure/azure-dev/cli/azd/cmd.(*initAction).Run(0xc0006896e0, {0x1251ec0, 0xc0000bc330})
        github.com/azure/azure-dev/cli/azd/cmd/init.go:222 +0xb45
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x1251ec0?, 0xc0000bc330?})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:127 +0x2e8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0xc00017a4f0, {0x1251ec0, 0xc0003b98f0}, 0xc000048e40)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/telemetry.go:85 +0x8b8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x1251ec0, 0xc0003b98f0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:125 +0x2a2
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*ExperimentationMiddleware).Run(0x10a3b96?, {0x1251ec0, 0xc0003b98f0}, 0xc000048e40)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/experimentation.go:64 +0x4d6
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x1251ec0, 0xc0003b98f0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:125 +0x2a2
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*DebugMiddleware).Run(0xc000692300, {0x1251ec0, 0xc0003b98f0}, 0xc000048e40)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/debug.go:48 +0x311
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x1251ec0, 0xc0003b98f0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:125 +0x2a2
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction(0xc00050c8a0, {0x1251ec0, 0xc0003b98f0}, 0xe1b460?, {0x12467c0?, 0xc0006896e0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:131 +0x226
github.com/azure/azure-dev/cli/azd/cmd.(*CobraBuilder).configureActionResolver.func1(0xc000504500, {0x198c080?, 0x0, 0x0})
        github.com/azure/azure-dev/cli/azd/cmd/cobra_builder.go:142 +0x4cf
github.com/spf13/cobra.(*Command).execute(0xc000504500, {0x198c080, 0x0, 0x0})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f9680)
        github.com/spf13/cobra@v1.3.
```

**To Reproduce**
Create a .NET Aspire Project that includes a single additional container:
```
IDistributedApplicationBuilder builder = DistributedApplication.CreateBuilder(args);

IResourceBuilder<ContainerResource> qdrant = builder.AddContainer("qdrant", "qdrant/qdrant", "latest")
                    .WithVolumeMount("./qdrant_storage", "/qdrant_storage")
                    .WithServiceBinding(6333, "http", "qdrant");
EndpointReference qdrantEndpoint = qdrant.GetEndpoint("qdrant");

builder.AddProject<Projects.ProjectName>("projectname")
                 .WithReference(qdrantEndpoint);

builder.Build().Run();
```

Without the container, it works flawlessly.

**Expected behavior**
Azd init runs successfully.

**Environment**
- Windows 10, 22H2 (10.0.19045)
- `az -v`
  ```
  azure-cli                         2.54.0
  
  core                              2.54.0
  telemetry                          1.1.0
  
  Extensions:
  azure-devops                      0.26.0
  
  Dependencies:
  msal                            1.24.0b2
  azure-mgmt-resource             23.1.0b2
  
  Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
  Extensions directory 'C:\Users\...\.azure\cliextensions'
  
  Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
  ```
- VS 17.9.0 Preview 1.0
- Relevant `dotnet -info`
  ```
  .NET SDK:
   Version:           8.0.100
   Commit:            57efcf1350
   Workload version:  8.0.100-manifests.71b9f198

   [aspire]
     Installationsquelle: VS 17.9.34310.174
     Manifestversion:    8.0.0-preview.1.23557.2/8.0.100
     Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.1.23557.2\WorkloadManifest.json
     Installationstyp:              Msi
  ```

Let me know if you need any additional info.

**Comment by vhvb1989** [comment]
The root cause is coming from `.WithServiceBinding(6333, "http", "qdrant");` 

azd is expecting to see the port in the manifest generated by Aspire, but the port is not there.  I've started a conversation with Aspire team to see if this is a bug on aspire generation, or if that's per design and azd should handle.

**Comment by vhvb1989** [comment]
Confirmed this is Aspire issue (on current preview1). Fix will be part of `preview2` for December release.

**Comment by vhvb1989** [comment]
Ran a test using daily build from Aspire (preview2) and this is issue is resolved:

![image](https://github.com/Azure/azure-dev/assets/24213737/849245e8-8d88-41fc-9503-a8d25c48097f)
