### ISSUE TITLE
devcenter - fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3437]
Seen occasionally on Windows-ci:

```
=== FAIL: cli/azd/pkg/devcenter Test_TemplateSource_ListTemplates/WithSingleDefaultValue (unknown)
fatal error: concurrent map read and map write

goroutine 97 [running]:
github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).devCenterList(0xc00013f6e0, {0xba9120, 0xed3760})
	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:184 +0x7e
github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*devCenterClient).host(0x6a8db8?, {0xba9120?, 0xed3760?}, 0xc000111180)
	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/developer_client.go:215 +0x2f
github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EntityListRequestBuilder[...]).createRequest(0x22, {0xba9120?, 0xed3760}, {0xaeee92, 0x3}, {0xc000152c30, 0x28})
	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/entity_list_request_builder.go:44 +0x6b
github.com/azure/azure-dev/cli/azd/pkg/devcentersdk.(*EnvironmentDefinitionListRequestBuilder).Get(0xc00047f950, {0xba9120, 0xed3760})
	D:/a/_work/1/s/cli/azd/pkg/devcentersdk/environment_definition_request_builders.go:41 +0x129
github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates.func3(0xe74560)
	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:85 +0x3fe
created by github.com/azure/azure-dev/cli/azd/pkg/devcenter.(*TemplateSource).ListTemplates in goroutine 94
	D:/a/_work/1/s/cli/azd/pkg/devcenter/template_source.go:73 +0x233
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3524605&view=logs&j=a24bcfce-df5c-5f85-8999-2d93251fa3c8&t=0f29edc0-91a9-5b1f-19bb-ae2082e49dbd&l=165

**Comment by rajeshkamal5050** [comment]
@wbreza @vhvb1989 added to backlog. Please pull it in if its frequent and impacting.
