### ISSUE TITLE
`Run Task: Start API` fails in the latest version of node

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/azure-dev#4655]
**Describe the issue:**
After running `Run Task: Start API` under the latest version of node: `v23.5.0` , the API start fails, as shown in the following figure:
![Image](https://github.com/user-attachments/assets/4c9bf46d-22d9-4f42-a012-babe9fb83fa4)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Run command `azd init -t <template> -b staging`.
3. Run command `azd up`.
4. Click F1, run task: `Start api and web`.

**Environment:**

- Template: todo-nodejs-mongo-terraform/todo-nodejs-mongo-aca/todo-nodejs-mongo-swa-func/todo-nodejs-mongo.
- Branch: staging
- OS: Windows, Mac.
- Azd version: azd version 1.12.0-beta.1-daily.4411118 (commit d3faad67144b8228f1c1a3a342953033db902bdc)
- Node version: v23.5.0 
- Npm version: 10.9.2

**Expected behavior:**
`Run Task: Start API` can be run successfully.

@rajeshkamal5050 for notification.

**Comment by JeffreyCA** [comment]
After modifying the `npm start` script from `node .` to `node --trace-deprecation .` in `package.json`, I got a more detailed error pointing to the use of some deprecated APIs in the `config` dependency:

```
(node:15258) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
    at _clone (/workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:1006:15)
    at Config.cloneDeep (/workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:1048:10)
    at /workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:1323:32
    at Array.forEach (<anonymous>)
    at util.extendDeep (/workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:1298:9)
    at /workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:653:12
    at Array.forEach (<anonymous>)
    at util.loadFileConfigs (/workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:650:16)
    at new Config (/workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:116:27)
    at Object.<anonymous> (/workspaces/todo-nodejs-mongo/src/api/node_modules/config/lib/config.js:1515:33)
```

This should be fixed by bumping the `config` dependency to `v3.3.12`: https://github.com/node-config/node-config/pull/764. We're currently using `v3.3.7`:

https://github.com/Azure/azure-dev/blob/27638ba2d2740a7a7ba3374d9782bb303863e87d/templates/todo/api/js/package.json#L30

**Comment by JeffreyCA** [comment]
> todo-nodejs-mongo-terraform/todo-nodejs-mongo-aca/todo-nodejs-mongo-swa-func/todo-nodejs-mongo.

@NanaXiong00 the issue should be fixed now in all of these templates (both `staging` and `main` branches), can you please confirm?

**Comment by NanaXiong00** [comment]
@JeffreyCA Thanks! Based on the latest code, i have tested in these templates on `staging` and `main` branches. The issue is fixed.
