### ISSUE TITLE
Error: failed to create or update service principal

### ISSUE THREAD

**Issue by marnixcox** [Azure/azure-dev#827]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 0.3.0-beta.1 (commit c5344160ed49bfda75281fba28b5e9ac7b96670e)`

**Output from `az version`** 
```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "application-insights": "0.1.7",
    "arcdata": "1.4.5",
    "init": "0.1.0",
    "managementpartner": "0.1.3"
  }
}
```
**Describe the bug**
Can you please advise if there is a way to do the "azd pipeline config --provider azdo" step, without automaticly creating the service principal, as most tenants and DevOps organisations don't want individual developers to have this level of access and have already setup a service connection ready to use.

```
Error: failed to create or update service principal: failed running az ad sp create-for-rbac: exit code: 1, stdout: , stderr: ERROR: Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation
```

**To Reproduce**
Set minimal user rights on Active Directory en run azd pipeline config --provider azdo

**Expected behavior**
Get the opportunity to set/select an existing service connection.

**Environment**
    * Visual Studio Code 1.71.2

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you see if the existing service-principal/connection can be used for AzDo?

**Comment by vhvb1989** [comment]
We need to add the support to use an existing service-principal.

Right now, no matter what provider is selected (github or Azure DevOps), `azd` creates a new service principal every time that `azd pipeline` is executed.

The only customization that azd supports is using the name of an existing service-principal. When this is set like `azd pipeline --principal-name some-service-principal-name` ,  azd would rotate the `secret-credentials` from that service-principal and use it to stablish the connection.

For the requested scenario, the customer would need to set:
- clientId
- tenantId
- client secret

for an existing service-principal.  (there's no way to fetch a service-principal's client secret without rotating the secret).

I need to define with PM what would it be the experience/flow for doing this.
- Should it be set in azure.yaml?
- should we add the 3 values as input arguments? 
- Set an option to use existing and prompt user to enter the values?
- Use env-vars to define the service-principal credentials and auto-detect with azd?
- Any other

@savannahostrowski @puicchan @jongio FYI, can you start thinking about what would you like here?  or if we don't want to support this (for any reason)

**Comment by savannahostrowski** [comment]
This seems like something we do want to support. I think that this likely falls into the larger effort of supporting developers using azd with non-azd created/existing infrastructure. We probably want to group this and other similar items under that epic/bucket (BYO-infrastructure).

**Comment by puicchan** [comment]
In enterprise scenario, developers typically do not have direct access or rights to create service principal. clientId, teanantId etc. are json output that is captured after running `az ad sp`. The secret should be captured and configured in GitHub Workflow or AzDo so it should not be something we store on azd side (dev won't have access.) @jongio @wbreza for input.

**Comment by ogimgio** [comment]
any update on this?

**Comment by mikkelh-SDU** [comment]
As @puicchan mentioned, as a developer without access or permissions to an existing service principal/infrastructure, my team and I, along with other teams in our organization, would greatly appreciate it if this feature could be prioritized.

Just here to raise interest in this feature and hopefully it gets picked up.

**Comment by jm-ra** [comment]
is there any kind of workaround?

**Comment by mikkelh-SDU** [comment]
> is there any kind of workaround?

In my case, we use landing zones and Azure DevOps projects, which come with service connections, so I just do not use the `azd pipeline config` command. Instead, I go into the DevOps project and manually point to the .yaml pipeline file.

**Comment by mikkelh-SDU** [comment]
Any updates on this? 😊

**Comment by vhvb1989** [comment]
@Hi @mikkelh-SDU 

starting in version 1.17.0, when you run `azd pipeline config`, you will see an option that lets you skip setting up the connection to Azure (Creating either SP or MSI). The process would just skip this part and go to ENV VARs set up.

**Comment by mikkelh-SDU** [comment]
> [@hi](https://github.com/hi) [@mikkelh-SDU](https://github.com/mikkelh-SDU)
> 
> starting in version 1.17.0, when you run `azd pipeline config`, you will see an option that lets you skip setting up the connection to Azure (Creating either SP or MSI). The process would just skip this part and go to ENV VARs set up.

Thats great news!!

I would like to see how it worked and started with a template "Starter - Bicep" from awesome AZD, but when i pressed the skip part it gives me a invalid memory address or nil pointer dereference

```
? Select how to authenticate the pipeline to Azure Skip authentication setup (for manually configured pipelines or existing set up)
  (✓) Done: Assigning read access role for Key Vault
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1abf646]

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/azdo.getDefinitionVariables(0xc0001adf50, 0x0, {{0x0, 0x0}, {0x20479f4, 0x5}, {0x2046fca, 0x4}, 0x0, 0x0}, ...)
        github.com/azure/azure-dev/cli/azd/pkg/azdo/pipeline.go:161 +0x426
github.com/azure/azure-dev/cli/azd/pkg/azdo.createAzureDevPipelineArgs({0xc000352b10, 0x24}, {0xc0002869e0, 0x1f}, {0xc00043ab50, 0xc}, 0x0, 0xc0001adf50, 0xc000592300, {{0x0, ...}, ...}, ...)
        github.com/azure/azure-dev/cli/azd/pkg/azdo/pipeline.go:246 +0x68f
github.com/azure/azure-dev/cli/azd/pkg/azdo.CreatePipeline({0x2286bf8, 0xc00032e1b0}, {0xc000352b10, 0x24}, {0x205b0a2, 0x10}, {0xc00043ab50, 0xc}, 0xc0002f4000, 0x0, ...)
        github.com/azure/azure-dev/cli/azd/pkg/azdo/pipeline.go:136 +0x4cf
github.com/azure/azure-dev/cli/azd/pkg/pipeline.(*AzdoCiProvider).configurePipeline(0xc000214aa0, {0x2286bf8, 0xc00032e1b0}, 0x208e532?, 0xc000490300)
        github.com/azure/azure-dev/cli/azd/pkg/pipeline/azdo_provider.go:815 +0x1ff
github.com/azure/azure-dev/cli/azd/pkg/pipeline.(*PipelineManager).Configure(0xc000462c00, {0x2286bf8, 0xc00032e1b0}, {0xc0005a3ac0, 0xb}, 0xc00016f320)
        github.com/azure/azure-dev/cli/azd/pkg/pipeline/pipeline_manager.go:726 +0x2cf5
github.com/azure/azure-dev/cli/azd/cmd.(*pipelineConfigAction).Run(0xc000214af0, {0x2286bf8, 0xc00032e1b0})
        github.com/azure/azure-dev/cli/azd/cmd/pipeline.go:186 +0x376
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x2286bf8, 0xc00032e1b0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:129 +0x429
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*LoginGuardMiddleware).Run(0xc00032f860, {0x2286bf8, 0xc00032e1b0}, 0xc000599940)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/login_guard.go:58 +0x89
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x2286bf8, 0xc00032e1b0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:112 +0x2b8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0xc00025a360, {0x2286bf8, 0xc0001bede0}, 0xc000599940)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/telemetry.go:81 +0x86e
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x2286bf8, 0xc0001bede0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:112 +0x2b8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*UxMiddleware).Run(0xc000008e10, {0x2286bf8, 0xc0001bede0}, 0xc000599940)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/ux.go:35 +0xa5
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x2286bf8, 0xc0001bede0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:112 +0x2b8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*DebugMiddleware).Run(0xc000008de0, {0x2286bf8, 0xc0001bede0}, 0xc000599940)
        github.com/azure/azure-dev/cli/azd/cmd/middleware/debug.go:51 +0x382
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x2286bf8, 0xc0001bede0})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:112 +0x2b8
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction(0xc0002a9380, {0x2286bf8, 0xc0001bede0}, 0xc000384900, {0xc0001c50a0, 0x1a})
        github.com/azure/azure-dev/cli/azd/cmd/middleware/middleware.go:133 +0x137
github.com/azure/azure-dev/cli/azd/cmd.(*CobraBuilder).configureActionResolver.func1(0xc000370f08, {0x2cf2b40, 0x0, 0x0})
        github.com/azure/azure-dev/cli/azd/cmd/cobra_builder.go:133 +0x37c
github.com/spf13/cobra.(*Command).execute(0xc000370f08, {0x2cf2b40, 0x0, 0x0})
        github.com/spf13/cobra@v1.9.1/command.go:1015 +0xa94
github.com/spf13/cobra.(*Command).ExecuteC(0xc000310608)
        github.com/spf13/cobra@v1.9.1/command.go:1148 +0x40c
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.9.1/command.go:1064
main.main()
        github.com/azure/azure-dev/cli/azd/main.go:65 +0x24b
```


Maybe I have done something wrong?

**Comment by vhvb1989** [comment]
@mikkelh-SDU , that's definitely a bug for AzureDevOps.  I will make it an issue and take a look.
Thanks for trying and reporting the issue.
https://github.com/Azure/azure-dev/issues/5438

**Comment by mikkelh-SDU** [comment]
> [@mikkelh-SDU](https://github.com/mikkelh-SDU) , that's definitely a bug for AzureDevOps. I will make it an issue and take a look. Thanks for trying and reporting the issue. [#5438](https://github.com/Azure/azure-dev/issues/5438)

Okay, I see — and thanks for picking it up so fast!
I’ll wait to see what you find and follow the issue in the meantime.
