### ISSUE TITLE
panic in `azd provision`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#977]
Reported from a private internal repo CI [run](https://github.com/Azure/scalable-web-app-pattern-dotnet/actions/runs/3315339940/jobs/5475808674)

```
Run azd provision --no-prompt

Infrastructure provisioning plan completed successfully
Provisioning Azure resources can take some time.

You can view detailed progress in the Azure Portal:
https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F***%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2F***daily2

panic: interface conversion: interface {} is bool, not string

goroutine 124 [running]:
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.CreateDeploymentOutput(...)
	/mnt/vss/_work/1/s/cli/azd/pkg/tools/azcli/deployments.go:197
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*azCli).DeployToSubscription(0x40?, {0xbda638, 0xc0003bbe90}, {0xc0000356ec?, 0x40f0ff?}, {0xc00002e18f, 0x18}, 0xc000038190, {0xc0004fa390, 0x23}, ...)
	/mnt/vss/_work/1/s/cli/azd/pkg/tools/azcli/deployments.go:117 +0x646
github.com/azure/azure-dev/cli/azd/pkg/infra.(*SubscriptionScope).Deploy(0x0?, {0xbda638?, 0xc0003bbe90?}, 0x40?, {0xc0004fa390?, 0x40?})
	/mnt/vss/_work/1/s/cli/azd/pkg/infra/scope.go:1[10](https://github.com/Azure/scalable-web-app-pattern-dotnet/actions/runs/3315339940/jobs/5475808674#step:5:11) +0x88
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).deployModule(0x0?, {0xbda638, 0xc0003bbe90}, {0xbdb960?, 0xc000[15](https://github.com/Azure/scalable-web-app-pattern-dotnet/actions/runs/3315339940/jobs/5475808674#step:5:16)c100?}, 0xc000483301?, {0xc0004fa390?, 0x5?})
	/mnt/vss/_work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:856 +0xdb
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).Deploy.func1(0xc0000242d0)
	/mnt/vss/_work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:228 +0x1f8
github.com/azure/azure-dev/cli/azd/pkg/async.(*InteractiveTaskWithProgress[...]).Run.func1()
	/mnt/vss/_work/1/s/cli/azd/pkg/async/task.go:191 +0x1a8
created by github.com/azure/azure-dev/cli/azd/pkg/async.(*InteractiveTaskWithProgress[...]).Run
	/mnt/vss/_work/1/s/cli/azd/pkg/async/task.go:[18](https://github.com/Azure/scalable-web-app-pattern-dotnet/actions/runs/3315339940/jobs/5475808674#step:5:19)6 +0x1cb
```

**Comment by vhvb1989** [comment]
Fixed on version azd version 0.3.0-beta.4 (released on 10/25)
