### ISSUE TITLE
[Issue] Panic when running azd up (nil pointer)

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#997]
**Output from `azd version`**

```
azd version 0.3.0-beta.4 (commit 2f4c6d14f8a9afcdaaff769f3fa010040f1e9120)
```

**Output from `az version`** 

```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Describe the bug**

When I opened https://github.com/pamelafox/django-on-azure in Codespaces and ran azd up, I got this error:

```
@pamelafox ➜ /workspaces/django-on-azure (main) $ azd up
? Please enter a new environment name: django-workshop-example
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code F4SFQSJJ5 to authenticate.
? Please select an Azure Subscription to use: 74. ca-pamelafox-demo-test (32ea8a26-5b40-4838-b6cb-be5c89a57c16)
? Please select an Azure location to use: 41. (US) East US 2 (eastus2)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x76f0a2]

goroutine 1 [running]:
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.NewResponseError(0x0)
        /home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.3/internal/exported/response_error.go:21 +0x42
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.NewResponseError(...)
        /home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.3/runtime/errors.go:18
github.com/azure/azure-dev/cli/azd/pkg/graphsdk.(*MeItemRequestBuilder).Get(0xc000014498, {0xbeb558, 0xc000385920})
        /mnt/vss/_work/1/s/cli/azd/pkg/graphsdk/me_request_builder.go:32 +0x12e
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*azCli).GetSignedInUserId(0xbeb558?, {0xbeb558, 0xc000385920})
        /mnt/vss/_work/1/s/cli/azd/pkg/tools/azcli/ad.go:36 +0x9c
github.com/azure/azure-dev/cli/azd/pkg/azureutil.GetCurrentPrincipalId({0xbeb558, 0xc000385920})
        /mnt/vss/_work/1/s/cli/azd/pkg/azureutil/principal.go:24 +0x4a
github.com/azure/azure-dev/cli/azd/cmd.ensureEnvironmentInitialized({0xbeb558, 0xc000385920}, {{0xc00002e380, 0x17}, {0x0, 0x0}, {0x0, 0x0}}, 0xc0004882d0, {0xbec958, ...})
        /mnt/vss/_work/1/s/cli/azd/cmd/util.go:271 +0x57d
github.com/azure/azure-dev/cli/azd/cmd.createAndInitEnvironment({0xbeb558, 0xc000385920}, 0xc0006f1430, 0xc000066070?, {0xbec958?, 0xc000364930?})
        /mnt/vss/_work/1/s/cli/azd/cmd/util.go:91 +0x29d
github.com/azure/azure-dev/cli/azd/cmd.(*initAction).Run(0xc0001346e0, {0xbeb558, 0xc000385920})
        /mnt/vss/_work/1/s/cli/azd/cmd/init.go:318 +0x1588
github.com/azure/azure-dev/cli/azd/cmd.(*upAction).runInit(0x0?, {0xbeb558?, 0xc000385920?})
        /mnt/vss/_work/1/s/cli/azd/cmd/up.go:109 +0x26
github.com/azure/azure-dev/cli/azd/cmd.(*upAction).Run(0xc0003856e0, {0xbeb558, 0xc000385920})
        /mnt/vss/_work/1/s/cli/azd/cmd/up.go:81 +0x2c
github.com/azure/azure-dev/cli/azd/cmd.BuildCmd[...].func1({0xbeb558?, 0xc000385620}, {0xf99518, 0x0?, 0x0?})
        /mnt/vss/_work/1/s/cli/azd/cmd/root.go:154 +0x157
github.com/azure/azure-dev/cli/azd/cmd.BuildCmd[...].func2.1()
        /mnt/vss/_work/1/s/cli/azd/cmd/root.go:162 +0x44
github.com/azure/azure-dev/cli/azd/cmd.runCmdWithTelemetry(0xc00038d900, 0xc0002bfa50)
        /mnt/vss/_work/1/s/cli/azd/cmd/root.go:176 +0x14e
github.com/azure/azure-dev/cli/azd/cmd.BuildCmd[...].func2({0xf99518?, 0x0?, 0x0?})
        /mnt/vss/_work/1/s/cli/azd/cmd/root.go:163 +0xb3
github.com/spf13/cobra.(*Command).execute(0xc00038d900, {0xf99518, 0x0, 0x0})
        /home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00034f680)
        /home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
main.main()
        /mnt/vss/_work/1/s/cli/azd/main.go:51 +0x1eb
@pamelafox ➜ /workspaces/django-on-azure (main) $ 
```

**To Reproduce**

1. Open https://github.com/pamelafox/django-on-azure in Codespaces
2. Run `azd up`

I'll keep trying different things to see if I can pinpoint why I'm getting a panic in this situation, as I've been able to run 'azd up' in other repos. 

**Environment**

Information on your environment: Online Codespaces, Microsoft Edge

**Comment by rajeshkamal5050** [comment]
@pamelafox do you get this issue locally for this repo? or just on codespaces?

**Comment by pamelafox** [comment]
For the same repo and the latest version of azd, I *am* able to run `azd up` successfully locally, getting everything provisioned. However, I can't open the devcontainer locally since I am on an M1 (https://github.com/Azure/azure-dev/issues/952), so I can only test running `azd up` outside of a devcontainer (in the global env). It's possible the same issue would happen locally in a devcontainer.

**Comment by pamelafox** [comment]
I was also able to run `azd up` in another repo in Codespaces today with the latest version of azd, so it doesn't seem to be just related to Codespaces overall, something more particular is happening.

**Comment by rajeshkamal5050** [comment]
> github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*azCli).GetSignedInUserId(0xbeb558?, {0xbeb558, 0xc000385920})
        /mnt/vss/_work/1/s/cli/azd/pkg/tools/azcli/ad.go:36 +0x9c
github.com/azure/azure-dev/cli/azd/pkg/azureutil.GetCurrentPrincipalId({0xbeb558, 0xc000385920})

@wbreza @vhvb1989 any recent changes w.r.t to consuming Go SDK's could have caused this to happen on Codespaces?

**Comment by rajeshkamal5050** [comment]
The stack trace kind of looks similar and is reported for all templates in #1005

**Comment by pamelafox** [comment]
Ah yes that does look like the same stack trace, and same environment. Feel free to merge these issues together.
